### ISSUE TITLE
Out of habits, I tend to type nord-0 instead of nord0. 

### ISSUE THREAD

**Issue by samyosm** [crumb1e/tailwind-nord#6]
I know the official name of the nord colors are nord0, nord1, and so on. But on Tailwind, they do not feel right and I am sure a lot of people have mistyped them. Instead of changing the names, I would suggest simply appending new names using the convention nord-0, nord-1, and so on.

**Comment by crumb1e** [comment]
Apologies for the delay! I like this idea, I'll approve your PR and get a release out later today 👍
